### ISSUE TITLE
一些些提议

### ISSUE THREAD

**Issue by Yowi** [hold-baby/label-img#1]
1、bgColor 无效。
2、初始化图片未居中（垂直居中）。

**Comment by hold-baby** [comment]
主要是最近换工作太忙了 等这段时间过了 就会修改的

**Comment by hold-baby** [comment]
加了个参数`imagePlacement: "center"`可以居中图片

**Comment by gclm** [comment]
这个参数是那个api 的啊

**Comment by hold-baby** [comment]
@gclm options 参数中

**Comment by gclm** [comment]
@hold-baby  我在实例demo上没找到这个啊。如果基于demo进行修改的话，那个options参数应该添加到哪里啊。
![image](https://user-images.githubusercontent.com/27618687/129846094-6730a086-4f94-4f04-a52d-f5648236a2ef.png)
