### ISSUE TITLE
请问vue可以用吗，怎样初始化，在template需要写啥？

### ISSUE THREAD

**Issue by finekewei** [hold-baby/label-img#11]
在线demo看着真香

**Comment by hold-baby** [comment]
生成 [实例](https://github.com/hold-baby/label-img#%E4%BD%BF%E7%94%A8) 挂载到 vue 的上下文
template 里给一个 div 挂载节点就可以

**Comment by hold-baby** [comment]
https://github.com/hold-baby/label-img/blob/main/example/instance.tsx

**Comment by finekewei** [comment]
已经欢快的用起来了，棒【香】，虽然没弄明白 demo中画完一个图形后，左边的图形list是怎么同步的

**Comment by hold-baby** [comment]
[监听创建事件](https://github.com/hold-baby/label-img/blob/main/example/listener.tsx) 回调中再去取最新的值展示出来
