### ISSUE TITLE
请问多边形可用长方形报错，这个是什么问题

### ISSUE THREAD

**Issue by lbmtt** [hold-baby/label-img#15]
如题，多边形可以用，在使用type是长方形的时候报错如下
![1655977334826](https://user-images.githubusercontent.com/35675629/175269346-2a227d11-80ce-41f5-b0e3-ef7e353f1934.png)

**Comment by hold-baby** [comment]
这样没办法分析，贴一下你的调用代码或者写个例子

**Comment by lbmtt** [comment]
vx：15122704518 您能加我一下，我给您发详细的吗

**Comment by hold-baby** [comment]
加你了
