### ISSUE TITLE
hello。大佬导入标注后的图片怎么搞

### ISSUE THREAD

**Issue by gclm** [hold-baby/label-img#5]
举个例子。目前这个图片我已经标注好了。目前我想获取标注后的图片

![image](https://user-images.githubusercontent.com/27618687/132835152-0cb20a88-e91d-4c8b-9123-46040f819d22.png)

我尝试用过html2canvas，发现不行
![image](https://user-images.githubusercontent.com/27618687/132835385-4aa61918-d36c-4b39-8c79-34d9b1f399a3.png)
![image](https://user-images.githubusercontent.com/27618687/132835364-5599524e-1e5c-476e-ba10-300ab4a6fda3.png)

**Comment by gclm** [comment]
我v：gclmit。如果感觉github issues 使用不方便的话，可以微信沟通

**Comment by hold-baby** [comment]
我加你微信
