### ISSUE TITLE
你好，想学习下你的代码。

### ISSUE THREAD

**Issue by jerryxin** [hold-baby/label-img#7]
你好，想学习下你的代码，能否帮忙解释下绘制图形之后点击拖动以及点击任意点拉伸缩放图形。这两个功能相关代码是哪些？代码写法太高级了，小白看起来太吃力。已star

**Comment by hold-baby** [comment]
https://github.com/hold-baby/label-img/blob/e5da96f3ce2e2f16e94ba0895cebdbe4402a27a9/src/Platform.ts#L147 事件都在这里进行初始化绑定

**Comment by jerryxin** [comment]
> https://github.com/hold-baby/label-img/blob/e5da96f3ce2e2f16e94ba0895cebdbe4402a27a9/src/Platform.ts#L147
> 
> 事件都在这里进行初始化绑定

感谢，矩形我已经有思路了
